### ISSUE TITLE
Installation Issue: "scons: ***Scons version 2.4.1 does not run under Python version 3.5.2"

### ISSUE THREAD

**Issue by donghee1025** [prisms-center/CASMcode#31]
When after I updated python version to 3.5, casm is no longer running. 

whenever I call "casm", I got these following error message. 

"dyld: Symbol not found: __ZNK5boost16re_detail_10600031cpp_regex_traits_implementationIcE17transform_primaryEPKcS4_
  Referenced from: /usr/local/bin/../lib/libcasm.dylib
  Expected in: /usr/local/opt/boost/lib/libboost_regex-mt.dylib
 in /usr/local/bin/../lib/libcasm.dylib
Trace/BPT trap: 5"

So, I tried to re-install casm code using scons 
"scons: *** SCons version 2.4.1 does not run under Python version 3.5.2.
Python 3 is not yet supported."

Do you have any suggestion?

Thank you

**Comment by bpuchala** [comment]
- We've primarily tested using Python 2.7 and not with Python 3, so for now the suggestion is to use Python 2 with CASM
- Not sure about the boost linking error, but shouldn't be due to Python. Maybe running 'scons configure' could help you figure out why it no longer links correctly. 
- We're transitioning to using GNU autotools instead of scons and I'll try to get that in the development branch soon
